version: "{build}"

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "9"

branches:
  except:
    - /v\d+\.\d+\.\d+/

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

cache:
  - node_modules

build: off

before_test:
  - npm prune

test_script:
  - cmd: 
      npm run-script test